### ISSUE TITLE
First character cut off from each command

### ISSUE THREAD

**Issue by dcrockwell** [paulserraino/babel-repl#1]
Notice `ReferenceError: elp is not defined`;

``` shell
babel-repl
> help
ReferenceError: elp is not defined
    at repl:3:1
    at REPLServer.defaultEval (/Users/dcrockwell/.nvm/versions/io.js/v2.3.1/lib/node_modules/babel-repl/index.js:45:27)
    at REPLServer.defaults.eval (/Users/dcrockwell/.nvm/versions/io.js/v2.3.1/lib/node_modules/babel-repl/index.js:12:19)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:308:12)
    at emitOne (events.js:77:13)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:209:10)
    at REPLServer.Interface._line (readline.js:548:8)
```

**Comment by dcrockwell** [comment]
Fixed in this pull request: https://github.com/paulserraino/babel-repl/pull/2

**Comment by paulserraino** [comment]
oh I see, I think know the source of the problem.

This is an unofficial "barebones" babel repl, a lot features that may be found in the offical babel repl (like `help`) are undefined in this repl, but if you wanted to implement a global name `help` (I don't recommend it) you would have to define `help` in the repl's context.

for example:
```js
var repl = require('repl');
var r = repl.start('> ');

r.context.help = function () {
  return 'babel help  docs';
}
```

check out the repl [node docs](https://nodejs.org/api/repl.html) for more info.


cheers :)

**Comment by raine** [comment]
```js
~ ❮❮❮ babel-repl
> 'foo'
SyntaxError: unknown: Unterminated string constant (1:3)
> 1 | foo'
    |    ^
```

Not quite usable as it is.

**Comment by paulserraino** [comment]
@raine I just submitted a patch that should fix this. I updated the `package.json` file, it now specifies the node engines (0.10.x). I believe there were some compatibility issues with using io.js.
